@PROJECT_HASH = 527057980290


###

curl --request GET \
  --url https://lab-06-get-customers-svc-{{PROJECT_HASH}}.us-central1.run.app/getcustomers \
  --header 'content-type: application/json' \
  --header 'user-agent: vscode-restclient'

